### ISSUE TITLE
unable to build the SDK.sln

### ISSUE THREAD

**Issue by zahraesm** [BelledonneCommunications/linphone-windows10#9]
has anyone ever been able to build and use this project in visual studio 2017?

i've been struggeling with it for a month now and no success. it seen to have some major flaws
@anders9ustafsson

**Comment by zahraesm** [comment]
@Wescoeur @DatBewar

**Comment by FurryWhiteLlama** [comment]
I'm also wondering? @zahraesm what errors do you run into?

My SDK.sln build does not work because '..\CsWrapper\**LinphoneWrapper.cs**' does not exist. What I don't understand is that it's looking for the file in the '..\CsWrapper' folder, which according to the CsWrapper project only gets copied when run, out of '..\OUTPUT\win10-ARM\share\linphonecs\LinphoneWrapper.cs' and that linephonecs folder doesn't exist. Does anyone know at which point does this file get created? 
When i ran **python prepare.py ARM** it didn't give any errors.

Other errors I get in the SDK build all look similar to this:
**Error C2059: syntax error: '(' (compiling source file C:\Users\user\Documents\GitHub\linphone-windows10\submodules\externals\libxml2\dict.c)** 
[C:\Users\user\Documents\GitHub\linphone-windows10\WORK\win10-ARM\Build\xml2\xml2.vcxproj] 
[C:\Users\user\Documents\GitHub\linphone-windows10\WORK\win10-ARM\cmake\EP_xml2.vcxproj]	SDK_ARM	C:\Program Files (x86)\Windows Kits\10\Include\10.0.17134.0\ucrt\**stdlib.h**	1193

**Comment by zahraesm** [comment]
@FurryWhiteLlama  hi i face the same issues as you. unfortunately i couldnt build this project after several attempts. FYI, i got the Linphonewrapper.cs  by the blame(annotate) feature in visual studio. let me know if you have any success.


btw, i switched to linphone-desktop : [https://github.com/BelledonneCommunications/linphone-desktop](url) it seemssome ppl have built this one successfully!!

**Comment by FurryWhiteLlama** [comment]
Hey @zahraesm, I got the project to work (although not all of it, but its good enough).
Unless you need the video call (MSWinRTVideo project) which I removed, just skip the SDK build by either getting the .nuget package their website and drop it in the OUTPUT folder or installing it through the package console directly for the Linphone.sln. Then it should work.

I needed it to build on ARM for Windows Handheld specifically so Linphone-desktop wouldn't help me. Now I can make VoIP calls, just not using video, but that was what I needed. Maybe this helps you? 

Btw thanks for the reply last week, I appreciate it. It was getting a bit frustrating and it's nice to know you're not suffering alone with these things sometimes! 👍

**Comment by omnitorsimon** [comment]
Hello, Ive mange to make it all build using 2017 (v141 toolchain) and SDK 10.0.17763.0. 

There was some issues with compiling, I changed the following.

- Copy my old LinphoneWrapper.cs to the CsWrapper folder. (Ive attched it here)
[LinphoneWrapper.cs.txt](https://github.com/BelledonneCommunications/linphone-windows10/files/3333502/LinphoneWrapper.cs.txt)

- Added: #pragma warning(disable : 4244) to linphone\submodules\mediastreamer2\videofilters/videoenc.c

- Added: #pragma warning(disable : 4244) to linphone\submodules\mediastreamer2\videofilters/videodec.c

- Checkout bctoolbox commit to "d867082"

- Change the prepare.py to not compile these: (["-DENABLE_SILK=NO"], ["-DENABLE_AMRNB=NO"],["-DENABLE_AMRWB=NO"]) Coudlnt make these work.

- When SDK.sln is started: right click on SDK in the solution, choose "Property" and choose "Debug Source Files" make sure these paths exsist on your machine.

I might be forgetting somthing, but a tip is that if you get an error like: 

**Error C2059: syntax error: '(' (compiling source file C:\Users\user\Documents\GitHub\linphone-windows10\submodules\externals\libxml2\dict.c)**

Look at the error surrounding that error in the output, I think they just missed a "," or somthing in the varibles.

Best of luck.

**Comment by SUHAILLL** [comment]
did you got solution? is new sdk here?

**Comment by anders9ustafsson** [comment]
Yes, I have managed to build it after some further experimenting. As far as I know, no new official SDK has been published.

**Comment by RCLuciano** [comment]
The file LinphoneWrapper.cs is generated and assigned automatically in the build phase.

I could compile the x64 and ARM without issues in Visual Studio 2019, the file LinphoneWrapper.cs is autogenerated and copied in the folder in the compilation.

Please follow the steps: https://gitlab.linphone.org/BC/public/linphone-windows10
